/**
 * The migration file conventions, enforced rather than documented.
 *
 * `migrations/_README.md` states these rules; a rule that only lives in a README is a rule that gets
 * broken by the next person in a hurry. All four of these were violated at least once in this repo's
 * short history, which is why they are tests and not prose.
 *
 * Cheap by construction: reads the migration directory, no database, no MJ imports.
 */
import { readFileSync, readdirSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import { describe, expect, it } from 'vitest';

const MIGRATIONS_DIR = fileURLToPath(new URL('../../../../migrations/', import.meta.url));

const files = readdirSync(MIGRATIONS_DIR)
    .filter((f) => f.endsWith('.sql'))
    .sort();

const read = (f: string) => readFileSync(MIGRATIONS_DIR + f, 'utf8');

/** Longest run of consecutive blank lines in a file. */
function longestBlankRun(text: string): number {
    let best = 0;
    let run = 0;
    for (const line of text.split('\n')) {
        run = line.trim() === '' ? run + 1 : 0;
        if (run > best) best = run;
    }
    return best;
}

/**
 * Whether a file carries CodeGen output. Detected by CodeGen's own banner text, which it writes into
 * every generated artifact — a marker CodeGen controls, so it cannot drift out of step with us.
 */
const hasCapture = (text: string) => text.includes('This was generated by the MemberJunction CodeGen tool');

it('there are migrations to check at all', () => {
    // Guards against the whole suite passing vacuously if the path ever moves.
    expect(files.length).toBeGreaterThan(0);
});

describe('the 50-blank-line separator', () => {
    for (const f of files) {
        const text = read(f);
        if (!hasCapture(text)) {
            it(`${f}: no capture, so no separator`, () => {
                // A hand-written-only migration with a 50-run means someone pasted a capture and
                // removed it badly, or copied a file as a template and left the gap behind.
                expect(longestBlankRun(text)).toBeLessThan(50);
            });
            continue;
        }
        it(`${f}: exactly 50 blank lines mark where CodeGen output begins`, () => {
            // EXACTLY 50, not "at least": the number is the signal. 49 or 51 means it was retyped
            // rather than copied, and a tool looking for the boundary by count would miss it.
            expect(longestBlankRun(text)).toBe(50);
        });
    }
});

describe('naming and ordering', () => {
    it('exactly one baseline, and it sorts first', () => {
        const baselines = files.filter((f) => f.startsWith('B'));
        expect(baselines).toHaveLength(1);
        expect(files[0]).toBe(baselines[0]);
    });

    it('every file matches the documented name shape', () => {
        for (const f of files) {
            // B|V + 12-digit timestamp + __v<version>__ + description + .sql
            expect(f, `${f} does not match the naming convention`).toMatch(/^[BV]\d{12}__v[\d.x]+__[A-Za-z0-9_]+\.sql$/);
        }
    });

    it('timestamps are strictly increasing — CI does not check this, so this does', () => {
        // The README warns that a migration numbered behind an applied one is SKIPPED silently on an
        // existing database and applied in the wrong order on a fresh one. Nothing else catches it.
        const stamps = files.map((f) => f.slice(1, 13));
        expect(stamps).toEqual([...stamps].sort());
        expect(new Set(stamps).size, 'two migrations share a timestamp').toBe(stamps.length);
    });
});

describe('schema references', () => {
    for (const f of files) {
        it(`${f}: uses the Flyway placeholder rather than the literal schema name`, () => {
            const text = read(f);
            // The literal name would work on this database and break under any other schema name,
            // which is precisely the failure that does not show up until someone else installs it.
            // Comments are exempt: they legitimately discuss the real name.
            const offenders = text
                .split('\n')
                .filter((l) => !l.trimStart().startsWith('--'))
                .filter((l) => l.includes('[__mj_BizAppsContracts]'));
            expect(offenders, `literal [__mj_BizAppsContracts] in SQL:\n${offenders.slice(0, 3).join('\n')}`).toEqual([]);
        });
    }

    it('no migration hardcodes NEWID() for a seeded primary key', () => {
        // A NEWID() key mints a NEW row on every rebuild instead of updating the existing one, so a
        // re-run silently doubles the seed. The baseline's ContractSequence row is the case that matters.
        for (const f of files) {
            const text = read(f);
            const sql = text.split('\n').filter((l) => !l.trimStart().startsWith('--'));
            const inserts = sql.filter((l) => /INSERT\s+INTO/i.test(l) && /NEWID\(\)/i.test(l));
            expect(inserts, `${f} INSERTs a NEWID() primary key`).toEqual([]);
        }
    });
});
