-- =============================================================================
-- V202608182000 — Contracts becomes a LAYERED base view: the flags + the
--                 CodeGen-generated inner view.
-- =============================================================================
-- Contracts adopts MJ's layered base views (MJ#3419): CodeGen writes its full
-- generated view under GeneratedBaseViewName (vwContractsGenerated) and the
-- APPLICATION owns BaseView (vwContracts) as a thin wrapper adding the derived
-- lifecycle columns. See the NEXT migration for the wrapper, plans/ERD-planned.md
-- §4.5 for what State means, and §7.2 for the derive-or-store rule that put those
-- columns in a view instead of on the table.
--
-- WHY THIS IS A SEPARATE FILE FROM THE BASELINE, given that pre-production
-- practice is to edit the baseline in place. Because the layering is a SEQUENCE,
-- not a state. The baseline's captured CodeGen output creates vwContracts at the
-- PUBLIC name — correct for a database whose Entity row still has the default
-- flags, which is what CodeGen's own Entity INSERT produces: it names neither
-- BaseViewGenerated nor GeneratedBaseViewName, so an `UPDATE` placed anywhere in
-- the baseline is a no-op against a row that does not exist yet. Setting the flags
-- has to happen AFTER registration and BEFORE the wrapper, and each step has to
-- carry the DDL that its own state implies. That is three files, and it is orders'
-- proven train (V202608131541 / V202608131542, verified by their stage-test).
--
-- WHY THE FLAGS ARE HERE AND NOT ONLY IN metadata/. The flags are declarative
-- metadata and metadata/entities/.entities.json IS the source of record — but
-- metadata is only consolidated into a migration at end-of-version. In the window
-- before that, a fresh environment runs migrate → codegen → sync push, and that
-- FIRST codegen, seeing BaseViewGenerated = 1, resolves its target to the PUBLIC
-- name and DROP/CREATEs vwContracts as a plain generated view, silently destroying
-- the hand-written wrapper. Execution is not gated by CodeGen's modified list;
-- only migration-log output is. Shipping the flags here means every environment
-- that migrates has them before any codegen can run.
--
-- Keyed by entity NAME, never by ID, and skips cleanly when the row is absent:
-- CodeGen may legitimately run after migrations on a database where this entity's
-- metadata does not exist yet.
-- =============================================================================

UPDATE [${mjSchema}].[Entity]
   SET [BaseViewGenerated] = 0,
       [GeneratedBaseViewName] = 'vwContractsGenerated'
 WHERE [Name] = 'MJ_BizApps_Contracts: Contracts'
   AND ([BaseViewGenerated] <> 0
        OR [GeneratedBaseViewName] IS NULL
        OR [GeneratedBaseViewName] <> 'vwContractsGenerated');
GO

-- =============================================================================
-- The generated INNER view, captured from the CodeGen run made after the flags
-- above were set. Copied verbatim from
-- `SQL Scripts/generated/__mj_BizAppsContracts/vwContractsGenerated.view.generated.sql`
-- with the schema name replaced by the Flyway placeholder — CodeGen writes that
-- file but does NOT emit the view into its run SQL log (it is treated as a
-- recurring script), so this one artifact has to be taken from the file rather
-- than from migrations/codegen/. Do not hand-edit it; re-copy it if the entity's
-- columns or its lookups change.
--
-- Note the joined name columns: ContractType, Company, CustomerOrganization,
-- PrimaryContactPerson, ContractTemplate, CreatingEntity, ParentContract. Those
-- are why D-23 requires every grid and picker to select the base view rather than
-- the table — the names are already here, so showing a UUID is a choice, not a
-- constraint.
-- =============================================================================

-----------------------------------------------------------------
-- SQL Code Generation
-- Entity: MJ_BizApps_Contracts: Contracts
-- Item: vwContractsGenerated
--
-- This was generated by the MemberJunction CodeGen tool.
-- This file should NOT be edited by hand.
-----------------------------------------------------------------

------------------------------------------------------------
----- BASE VIEW FOR ENTITY:      MJ_BizApps_Contracts: Contracts
-----               SCHEMA:      __mj_BizAppsContracts
-----               BASE TABLE:  Contract
-----               PRIMARY KEY: ID
------------------------------------------------------------
IF OBJECT_ID('[${flyway:defaultSchema}].[vwContractsGenerated]', 'V') IS NOT NULL
    DROP VIEW [${flyway:defaultSchema}].[vwContractsGenerated];
GO

CREATE VIEW [${flyway:defaultSchema}].[vwContractsGenerated]
AS
SELECT
    c.*,
    mjBizAppsContractsContractType_ContractTypeID.[Name] AS [ContractType],
    MJCompany_CompanyID.[Name] AS [Company],
    mjBizAppsCommonOrganization_CustomerOrganizationID.[Name] AS [CustomerOrganization],
    mjBizAppsCommonPerson_PrimaryContactPersonID.[FirstName] AS [PrimaryContactPerson],
    mjBizAppsContractsContractTemplate_ContractTemplateID.[Name] AS [ContractTemplate],
    MJEntity_CreatingEntityID.[Name] AS [CreatingEntity],
    mjBizAppsContractsContract_ParentContractID.[ContractNumber] AS [ParentContract],
    mjBizAppsContractsContract_SupersededByContractID.[ContractNumber] AS [SupersededByContract],
    root_ParentContractID.RootID AS [RootParentContractID],
    root_SupersededByContractID.RootID AS [RootSupersededByContractID]
FROM
    [${flyway:defaultSchema}].[Contract] AS c
INNER JOIN
    [${flyway:defaultSchema}].[ContractType] AS mjBizAppsContractsContractType_ContractTypeID
  ON
    [c].[ContractTypeID] = mjBizAppsContractsContractType_ContractTypeID.[ID]
INNER JOIN
    [__mj].[Company] AS MJCompany_CompanyID
  ON
    [c].[CompanyID] = MJCompany_CompanyID.[ID]
INNER JOIN
    [__mj_BizAppsCommon].[Organization] AS mjBizAppsCommonOrganization_CustomerOrganizationID
  ON
    [c].[CustomerOrganizationID] = mjBizAppsCommonOrganization_CustomerOrganizationID.[ID]
LEFT OUTER JOIN
    [__mj_BizAppsCommon].[Person] AS mjBizAppsCommonPerson_PrimaryContactPersonID
  ON
    [c].[PrimaryContactPersonID] = mjBizAppsCommonPerson_PrimaryContactPersonID.[ID]
LEFT OUTER JOIN
    [${flyway:defaultSchema}].[ContractTemplate] AS mjBizAppsContractsContractTemplate_ContractTemplateID
  ON
    [c].[ContractTemplateID] = mjBizAppsContractsContractTemplate_ContractTemplateID.[ID]
LEFT OUTER JOIN
    [__mj].[Entity] AS MJEntity_CreatingEntityID
  ON
    [c].[CreatingEntityID] = MJEntity_CreatingEntityID.[ID]
LEFT OUTER JOIN
    [${flyway:defaultSchema}].[Contract] AS mjBizAppsContractsContract_ParentContractID
  ON
    [c].[ParentContractID] = mjBizAppsContractsContract_ParentContractID.[ID]
LEFT OUTER JOIN
    [${flyway:defaultSchema}].[Contract] AS mjBizAppsContractsContract_SupersededByContractID
  ON
    [c].[SupersededByContractID] = mjBizAppsContractsContract_SupersededByContractID.[ID]
OUTER APPLY
    [${flyway:defaultSchema}].[fnContractParentContractID_GetRootID]([c].[ID], [c].[ParentContractID]) AS root_ParentContractID
OUTER APPLY
    [${flyway:defaultSchema}].[fnContractSupersededByContractID_GetRootID]([c].[ID], [c].[SupersededByContractID]) AS root_SupersededByContractID
GO
IF OBJECT_ID('[${flyway:defaultSchema}].[vwContracts]', 'V') IS NOT NULL
BEGIN
    EXEC sp_executesql N'GRANT SELECT ON [${flyway:defaultSchema}].[vwContracts] TO [cdp_UI], [cdp_Developer], [cdp_Integration]';
END

GO

-- =============================================================================
-- CODEGEN CAPTURE from the same run (post-flags). Regenerated Contract Template
-- Modification objects — CodeGen re-emits an entity's view and CRUD procedures
-- when its relationship metadata changes, and item 2's `Modifications` collection
-- declaration is that change.
-- =============================================================================

/* SQL text to update existing entities from schema */
EXEC [${mjSchema}].[spUpdateExistingEntitiesFromSchema] @ExcludedSchemaNames='sys,staging,dbo,${mjSchema},${mjSchema}_BizAppsAccounting,${mjSchema}_BizAppsCommon,${mjSchema}_BizAppsOrders,${mjSchema}_BizAppsTasks';

/* SQL text to update entity field related entity name field map for entity field ID 433E610E-1199-4A89-A3BE-23EEE91BB6B3 */
EXEC [${mjSchema}].[spUpdateEntityFieldRelatedEntityNameFieldMap] @EntityFieldID='433E610E-1199-4A89-A3BE-23EEE91BB6B3', @RelatedEntityNameFieldMap='ParentContract';

/* SQL text to update entity field related entity name field map for entity field ID FDA34007-6E79-4A3D-AC5A-3813DB33E863 */
EXEC [${mjSchema}].[spUpdateEntityFieldRelatedEntityNameFieldMap] @EntityFieldID='FDA34007-6E79-4A3D-AC5A-3813DB33E863', @RelatedEntityNameFieldMap='SupersededByContract';

/* SQL text to update existing entity fields from schema */
EXEC [${mjSchema}].[spUpdateExistingEntityFieldsFromSchema] @ExcludedSchemaNames='sys,staging,dbo,${mjSchema},${mjSchema}_BizAppsAccounting,${mjSchema}_BizAppsCommon,${mjSchema}_BizAppsOrders,${mjSchema}_BizAppsTasks';

/* SQL text to set default column width where needed */
EXEC [${mjSchema}].[spSetDefaultColumnWidthWhereNeeded] @ExcludedSchemaNames='sys,staging,dbo,${mjSchema},${mjSchema}_BizAppsAccounting,${mjSchema}_BizAppsCommon,${mjSchema}_BizAppsOrders,${mjSchema}_BizAppsTasks';

/* SQL text to sync schema info from database schemas */
EXEC [${mjSchema}].[spUpdateSchemaInfoFromDatabase] @ExcludedSchemaNames='sys,staging,dbo,${mjSchema},${mjSchema}_BizAppsAccounting,${mjSchema}_BizAppsCommon,${mjSchema}_BizAppsOrders,${mjSchema}_BizAppsTasks';

/* SQL text to update entity field related entity name field map for entity field ID 9D1ECADE-25C0-4A9C-912A-6B993C5AFD35 */
EXEC [${mjSchema}].[spUpdateEntityFieldRelatedEntityNameFieldMap] @EntityFieldID='9D1ECADE-25C0-4A9C-912A-6B993C5AFD35', @RelatedEntityNameFieldMap='Contract';

/* SQL text to update entity field related entity name field map for entity field ID 51331345-4AE4-4882-959A-6046CBBDDACE */
EXEC [${mjSchema}].[spUpdateEntityFieldRelatedEntityNameFieldMap] @EntityFieldID='51331345-4AE4-4882-959A-6046CBBDDACE', @RelatedEntityNameFieldMap='ContractTemplateProvision';

/* Base View SQL for MJ_BizApps_Contracts: Contract Template Modifications */
-----------------------------------------------------------------
-- SQL Code Generation
-- Entity: MJ_BizApps_Contracts: Contract Template Modifications
-- Item: vwContractTemplateModifications
--
-- This was generated by the MemberJunction CodeGen tool.
-- This file should NOT be edited by hand.
-----------------------------------------------------------------

------------------------------------------------------------
----- BASE VIEW FOR ENTITY:      MJ_BizApps_Contracts: Contract Template Modifications
-----               SCHEMA:      ${flyway:defaultSchema}
-----               BASE TABLE:  ContractTemplateModification
-----               PRIMARY KEY: ID
------------------------------------------------------------
IF OBJECT_ID('[${flyway:defaultSchema}].[vwContractTemplateModifications]', 'V') IS NOT NULL
    DROP VIEW [${flyway:defaultSchema}].[vwContractTemplateModifications];
GO

CREATE VIEW [${flyway:defaultSchema}].[vwContractTemplateModifications]
AS
SELECT
    c.*,
    mjBizAppsContractsContract_ContractID.[ContractNumber] AS [Contract],
    mjBizAppsContractsContractTemplateProvision_ContractTemplateProvisionID.[ProvisionNumber] AS [ContractTemplateProvision]
FROM
    [${flyway:defaultSchema}].[ContractTemplateModification] AS c
INNER JOIN
    [${flyway:defaultSchema}].[Contract] AS mjBizAppsContractsContract_ContractID
  ON
    [c].[ContractID] = mjBizAppsContractsContract_ContractID.[ID]
INNER JOIN
    [${flyway:defaultSchema}].[ContractTemplateProvision] AS mjBizAppsContractsContractTemplateProvision_ContractTemplateProvisionID
  ON
    [c].[ContractTemplateProvisionID] = mjBizAppsContractsContractTemplateProvision_ContractTemplateProvisionID.[ID]
GO
GRANT SELECT ON [${flyway:defaultSchema}].[vwContractTemplateModifications] TO [cdp_UI], [cdp_Developer], [cdp_Integration];

/* Base View Permissions SQL for MJ_BizApps_Contracts: Contract Template Modifications */
-----------------------------------------------------------------
-- SQL Code Generation
-- Entity: MJ_BizApps_Contracts: Contract Template Modifications
-- Item: Permissions for vwContractTemplateModifications
--
-- This was generated by the MemberJunction CodeGen tool.
-- This file should NOT be edited by hand.
-----------------------------------------------------------------

GRANT SELECT ON [${flyway:defaultSchema}].[vwContractTemplateModifications] TO [cdp_UI], [cdp_Developer], [cdp_Integration];

/* spCreate SQL for MJ_BizApps_Contracts: Contract Template Modifications */
-----------------------------------------------------------------
-- SQL Code Generation
-- Entity: MJ_BizApps_Contracts: Contract Template Modifications
-- Item: spCreateContractTemplateModification
--
-- This was generated by the MemberJunction CodeGen tool.
-- This file should NOT be edited by hand.
-----------------------------------------------------------------

------------------------------------------------------------
----- CREATE PROCEDURE FOR ContractTemplateModification
------------------------------------------------------------
IF OBJECT_ID('[${flyway:defaultSchema}].[spCreateContractTemplateModification]', 'P') IS NOT NULL
    DROP PROCEDURE [${flyway:defaultSchema}].[spCreateContractTemplateModification];
GO

CREATE PROCEDURE [${flyway:defaultSchema}].[spCreateContractTemplateModification]
    @ID uniqueidentifier = NULL,
    @ContractID uniqueidentifier,
    @ContractTemplateProvisionID uniqueidentifier,
    @ModificationText_Clear bit = 0,
    @ModificationText nvarchar(MAX) = NULL,
    @Notes_Clear bit = 0,
    @Notes nvarchar(MAX) = NULL
AS
BEGIN
    SET NOCOUNT ON;
    DECLARE @InsertedRow TABLE ([ID] UNIQUEIDENTIFIER)

    IF @ID IS NOT NULL
    BEGIN
        -- User provided a value, use it
        INSERT INTO [${flyway:defaultSchema}].[ContractTemplateModification]
            (
                [ID],
                [ContractID],
                [ContractTemplateProvisionID],
                [ModificationText],
                [Notes]
            )
        OUTPUT INSERTED.[ID] INTO @InsertedRow
        VALUES
            (
                @ID,
                @ContractID,
                @ContractTemplateProvisionID,
                CASE WHEN @ModificationText_Clear = 1 THEN NULL ELSE ISNULL(@ModificationText, NULL) END,
                CASE WHEN @Notes_Clear = 1 THEN NULL ELSE ISNULL(@Notes, NULL) END
            )
    END
    ELSE
    BEGIN
        -- No value provided, let database use its default (e.g., NEWSEQUENTIALID())
        INSERT INTO [${flyway:defaultSchema}].[ContractTemplateModification]
            (
                [ContractID],
                [ContractTemplateProvisionID],
                [ModificationText],
                [Notes]
            )
        OUTPUT INSERTED.[ID] INTO @InsertedRow
        VALUES
            (
                @ContractID,
                @ContractTemplateProvisionID,
                CASE WHEN @ModificationText_Clear = 1 THEN NULL ELSE ISNULL(@ModificationText, NULL) END,
                CASE WHEN @Notes_Clear = 1 THEN NULL ELSE ISNULL(@Notes, NULL) END
            )
    END
    -- return the new record from the base view, which might have some calculated fields
    SELECT * FROM [${flyway:defaultSchema}].[vwContractTemplateModifications] WHERE [ID] = (SELECT [ID] FROM @InsertedRow)
END
GO
GRANT EXECUTE ON [${flyway:defaultSchema}].[spCreateContractTemplateModification] TO [cdp_Developer], [cdp_Integration];

/* spCreate Permissions for MJ_BizApps_Contracts: Contract Template Modifications */

GRANT EXECUTE ON [${flyway:defaultSchema}].[spCreateContractTemplateModification] TO [cdp_Developer], [cdp_Integration];

/* spUpdate SQL for MJ_BizApps_Contracts: Contract Template Modifications */
-----------------------------------------------------------------
-- SQL Code Generation
-- Entity: MJ_BizApps_Contracts: Contract Template Modifications
-- Item: spUpdateContractTemplateModification
--
-- This was generated by the MemberJunction CodeGen tool.
-- This file should NOT be edited by hand.
-----------------------------------------------------------------

------------------------------------------------------------
----- UPDATE PROCEDURE FOR ContractTemplateModification
------------------------------------------------------------
IF OBJECT_ID('[${flyway:defaultSchema}].[spUpdateContractTemplateModification]', 'P') IS NOT NULL
    DROP PROCEDURE [${flyway:defaultSchema}].[spUpdateContractTemplateModification];
GO

CREATE PROCEDURE [${flyway:defaultSchema}].[spUpdateContractTemplateModification]
    @ID uniqueidentifier,
    @ContractID uniqueidentifier = NULL,
    @ContractTemplateProvisionID uniqueidentifier = NULL,
    @ModificationText_Clear bit = 0,
    @ModificationText nvarchar(MAX) = NULL,
    @Notes_Clear bit = 0,
    @Notes nvarchar(MAX) = NULL
AS
BEGIN
    SET NOCOUNT ON;
    UPDATE
        [${flyway:defaultSchema}].[ContractTemplateModification]
    SET
        [ContractID] = ISNULL(@ContractID, [ContractID]),
        [ContractTemplateProvisionID] = ISNULL(@ContractTemplateProvisionID, [ContractTemplateProvisionID]),
        [ModificationText] = CASE WHEN @ModificationText_Clear = 1 THEN NULL ELSE ISNULL(@ModificationText, [ModificationText]) END,
        [Notes] = CASE WHEN @Notes_Clear = 1 THEN NULL ELSE ISNULL(@Notes, [Notes]) END
    WHERE
        [ID] = @ID

    -- Check if the update was successful
    IF @@ROWCOUNT = 0
        -- Nothing was updated, return no rows, but column structure from base view intact, semantically correct this way.
        SELECT TOP 0 * FROM [${flyway:defaultSchema}].[vwContractTemplateModifications] WHERE 1=0
    ELSE
        -- Return the updated record so the caller can see the updated values and any calculated fields
        SELECT
                                        *
                                    FROM
                                        [${flyway:defaultSchema}].[vwContractTemplateModifications]
                                    WHERE
                                        [ID] = @ID
                                    
END
GO

GRANT EXECUTE ON [${flyway:defaultSchema}].[spUpdateContractTemplateModification] TO [cdp_Developer], [cdp_Integration]
GO

------------------------------------------------------------
----- TRIGGER FOR __mj_UpdatedAt field for the ContractTemplateModification table
------------------------------------------------------------
IF OBJECT_ID('[${flyway:defaultSchema}].[trgUpdateContractTemplateModification]', 'TR') IS NOT NULL
    DROP TRIGGER [${flyway:defaultSchema}].[trgUpdateContractTemplateModification];
GO
CREATE TRIGGER [${flyway:defaultSchema}].trgUpdateContractTemplateModification
ON [${flyway:defaultSchema}].[ContractTemplateModification]
AFTER UPDATE
AS
BEGIN
    SET NOCOUNT ON;
    UPDATE
        [${flyway:defaultSchema}].[ContractTemplateModification]
    SET
        __mj_UpdatedAt = GETUTCDATE()
    FROM
        [${flyway:defaultSchema}].[ContractTemplateModification] AS _organicTable
    INNER JOIN
        INSERTED AS I ON
        _organicTable.[ID] = I.[ID];
END;
GO

/* spUpdate Permissions for MJ_BizApps_Contracts: Contract Template Modifications */

GRANT EXECUTE ON [${flyway:defaultSchema}].[spUpdateContractTemplateModification] TO [cdp_Developer], [cdp_Integration];

/* spDelete SQL for MJ_BizApps_Contracts: Contract Template Modifications */
-----------------------------------------------------------------
-- SQL Code Generation
-- Entity: MJ_BizApps_Contracts: Contract Template Modifications
-- Item: spDeleteContractTemplateModification
--
-- This was generated by the MemberJunction CodeGen tool.
-- This file should NOT be edited by hand.
-----------------------------------------------------------------

------------------------------------------------------------
----- DELETE PROCEDURE FOR ContractTemplateModification
------------------------------------------------------------
IF OBJECT_ID('[${flyway:defaultSchema}].[spDeleteContractTemplateModification]', 'P') IS NOT NULL
    DROP PROCEDURE [${flyway:defaultSchema}].[spDeleteContractTemplateModification];
GO

CREATE PROCEDURE [${flyway:defaultSchema}].[spDeleteContractTemplateModification]
    @ID uniqueidentifier
AS
BEGIN
    SET NOCOUNT ON;

    DELETE FROM
        [${flyway:defaultSchema}].[ContractTemplateModification]
    WHERE
        [ID] = @ID


    -- Check if the delete was successful
    IF @@ROWCOUNT = 0
        SELECT NULL AS [ID] -- Return NULL for all primary key fields to indicate no record was deleted
    ELSE
        SELECT @ID AS [ID] -- Return the primary key values to indicate we successfully deleted the record
END
GO
GRANT EXECUTE ON [${flyway:defaultSchema}].[spDeleteContractTemplateModification] TO [cdp_Developer], [cdp_Integration];

/* spDelete Permissions for MJ_BizApps_Contracts: Contract Template Modifications */

GRANT EXECUTE ON [${flyway:defaultSchema}].[spDeleteContractTemplateModification] TO [cdp_Developer], [cdp_Integration];

/* Generated Validation Functions for MJ_BizApps_Contracts: Contract Sequences */
-- CHECK constraint for MJ_BizApps_Contracts: Contract Sequences: Field: ID was newly set or modified since the last generation of the validation function, the code was regenerated and updating the GeneratedCode table with the new generated validation function
INSERT INTO [${mjSchema}].[GeneratedCode] ([CategoryID], [GeneratedByModelID], [GeneratedAt], [Language], [Status], [Source], [Code], [Description], [Name], [LinkedEntityID], [LinkedRecordPrimaryKey])
                      VALUES ((SELECT [ID] FROM [${mjSchema}].[vwGeneratedCodeCategories] WHERE [Name]='CodeGen: Validators'), 'C43229F6-4CC8-4838-9D04-03419A2DA191', GETUTCDATE(), 'TypeScript', 'Approved', '([ID]=(1))', 'public ValidateIdIsOne(result: ValidationResult) {
	if (this.ID !== 1) {
		result.Errors.push(new ValidationErrorInfo(
			"ID",
			"The ID must be equal to 1.",
			this.ID,
			ValidationErrorType.Failure
		));
	}
}', 'The ID of this record must be exactly 1, which restricts the table to a single configuration or system row.', 'ValidateIdIsOne', 'DF238F34-2837-EF11-86D4-6045BDEE16E6', '9F76A3FC-F70D-4299-8A95-51F210C2D0C7');

