-- =============================================================================
-- Contract.PredictedRenewalRiskBand: the value list CodeGen derives from its CHECK
-- =============================================================================
-- V202609202354 added the column with CK_Contract_PredictedRenewalRiskBand
-- (Low, Medium, High, Critical) but shipped no EntityFieldValue rows. CodeGen derives
-- the four rows from the CHECK constraint and sets ValueListType = 'List' on the field,
-- and the committed entity class and Zod schema already type the field as that union.
-- A host installs by running migrations only and never runs CodeGen for this schema,
-- so without this file it has the typed code but no value list: no dropdown and no
-- metadata-level validation (the CHECK still rejects other values).
--
-- No schema change: this file is the CodeGen capture alone. It is the value-list part
-- of a CodeGen run against a database built from migrations (MJ core v6.1.5,
-- bizapps-common v5.50.2, bizapps-tasks v1.6.2, then this repo) after `mj sync push`.
-- The same run also re-emitted vwContractsGenerated and the three Contract procedures,
-- because a field change marks the entity modified; they differ from the shipped
-- definitions only by a trailing semicolon, so they are left out.


















































-- =============================================================================
-- CODEGEN OUTPUT (MJ 6.1.5), value-list statements only.
-- This was generated by the MemberJunction CodeGen tool. Do not edit by hand.
-- =============================================================================

/* SQL text to insert entity field value with ID f9404ebe-5434-4725-bedd-397ca8acf877 */
INSERT INTO [${mjSchema}].[EntityFieldValue]
                                       ([ID], [EntityFieldID], [Sequence], [Value], [Code], [__mj_CreatedAt], [__mj_UpdatedAt])
                                    VALUES
                                       ('f9404ebe-5434-4725-bedd-397ca8acf877', 'E25C8E07-F5DC-4D15-9EF4-56F51111575E', 1, 'Critical', 'Critical', GETUTCDATE(), GETUTCDATE());

/* SQL text to insert entity field value with ID 1158e600-d245-47b2-96a6-2a11261d0645 */
INSERT INTO [${mjSchema}].[EntityFieldValue]
                                       ([ID], [EntityFieldID], [Sequence], [Value], [Code], [__mj_CreatedAt], [__mj_UpdatedAt])
                                    VALUES
                                       ('1158e600-d245-47b2-96a6-2a11261d0645', 'E25C8E07-F5DC-4D15-9EF4-56F51111575E', 2, 'High', 'High', GETUTCDATE(), GETUTCDATE());

/* SQL text to insert entity field value with ID 6ef178b2-0cbf-4472-bb56-35ae9278d500 */
INSERT INTO [${mjSchema}].[EntityFieldValue]
                                       ([ID], [EntityFieldID], [Sequence], [Value], [Code], [__mj_CreatedAt], [__mj_UpdatedAt])
                                    VALUES
                                       ('6ef178b2-0cbf-4472-bb56-35ae9278d500', 'E25C8E07-F5DC-4D15-9EF4-56F51111575E', 3, 'Low', 'Low', GETUTCDATE(), GETUTCDATE());

/* SQL text to insert entity field value with ID d3f12a28-83c7-4464-989e-6dfb25532fb4 */
INSERT INTO [${mjSchema}].[EntityFieldValue]
                                       ([ID], [EntityFieldID], [Sequence], [Value], [Code], [__mj_CreatedAt], [__mj_UpdatedAt])
                                    VALUES
                                       ('d3f12a28-83c7-4464-989e-6dfb25532fb4', 'E25C8E07-F5DC-4D15-9EF4-56F51111575E', 4, 'Medium', 'Medium', GETUTCDATE(), GETUTCDATE());

/* SQL text to update ValueListType for entity field ID E25C8E07-F5DC-4D15-9EF4-56F51111575E */
UPDATE [${mjSchema}].[EntityField] SET ValueListType='List' WHERE ID='E25C8E07-F5DC-4D15-9EF4-56F51111575E';
